<?php declare(strict_types=1);

namespace Commands;

use Dotenv\Dotenv;
use GuzzleHttp\Client;
use GuzzleHttp\Event\EndEvent;
use GuzzleHttp\Event\ProgressEvent;
use League\Flysystem\Adapter\Local;
use Symfony\Component\Console\Helper\ProgressBar;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use ZipArchive;

class Install extends BuildCommand
{
    const ENV = <<<'ENV'
# This file was generated by the shopware composer shell installer
# Shop environment and database connection
SHOPWARE_ENV="dev"

# The URL has priority over the other values, so only one parameter needs to be set in production environments
DATABASE_URL="mysql://%3$s:%4$s@%1$s:%5$s/%2$s"

# If e.g. the password contains special chars not allowed in a URL, you can define each parameter by itself instead
DB_HOST="%1$s"
DB_DATABASE="%2$s"
DB_USERNAME="%3$s"
DB_PASSWORD="%4$s"
DB_PORT="%5$s"

# Installation configuration (can be removed after installation)
ADMIN_EMAIL="%6$s"
ADMIN_NAME="%7$s"
ADMIN_USERNAME="%8$s"
ADMIN_PASSWORD="%9$s"
SHOP_URL="%10$s"

IMPORT_DEMODATA=%11$s

ENV;

    /**
     * @var array
     */
    private $env = [];

    /**
     * @var ProgressBar
     */
    private $progress;

    protected function configure()
    {
        $this->addOption('skip-images', null, InputOption::VALUE_NONE);
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        /** @var Local $adapter */
        $adapter = $this->filesystem->getAdapter();
        $io = new SymfonyStyle($input, $output);

        $this->showBanner($output);

        if (!$this->envFileExists()) {
            if (!$input->isInteractive()) {
                $io->error('The .env file can only be generated in interactive mode.');
                return 1;
            }

            $io->title('Hi there! We need to configure your shop before proceeding any further, please complete the following fields.');
            $this->createEnvFileInteractive($io);

            (new Dotenv($adapter->applyPathPrefix('.')))->load();
        }

        if ($input->isInteractive() && !$io->confirm(sprintf('Start installation? This will drop the database %s!', getenv('DATABASE_URL')), false)) {
            $io->writeln('Not touching the database, have fun!');

            return 0;
        }

        $this->rebootApplication();

        $this->executeCommand('sw:database:setup --steps=drop,create,import', $output);

        if (getenv('IMPORT_DEMODATA') === 'y') {
            $io->writeln('Importing demo data please wait...');
            $this->executeCommand('sw:database:setup --steps=importDemodata', $output);
        }

        $this->createSymlinks();

        $this->executeCommand(sprintf('sw:database:setup --steps=setupShop --shop-url="%s"', getenv('SHOP_URL')), $output);
        $this->executeCommand('sw:snippets:to:db --include-plugins', $output);
        $this->executeCommand('sw:theme:initialize', $output);
        $this->executeCommand('sw:firstrunwizard:disable', $output);
        $this->executeCommand('sw:plugin:deactivate SwagUpdate', $output);
        $this->executeCommand(sprintf(
            'sw:admin:create --name="%s" --email="%s" --username="%s" --password="%s"',
            getenv('ADMIN_NAME'),
            getenv('ADMIN_EMAIL'),
            getenv('ADMIN_USERNAME'),
            getenv('ADMIN_PASSWORD')
        ), $output);

        if (!$input->hasOption('skip-images') && getenv('IMPORT_DEMODATA') === 'y' && $io->confirm('Do you want to install the images (~285MB) for the installed demo data? cURL is required.')) {
            $client = new Client();

            $request = $client->createRequest('GET', 'http://releases.s3.shopware.com/test_images_since_5.1.zip', [
                'save_to' => $adapter->applyPathPrefix('images.zip'),
            ]);

            $request->getEmitter()->on('progress', function (ProgressEvent $event) use ($io) {
                if ($this->progress instanceof ProgressBar) {
                    $this->progress->setProgress($event->downloaded);
                } elseif ($event->downloadSize) {
                    $this->progress = $io->createProgressBar($event->downloadSize);
                }
            });

            $request->getEmitter()->on('end', function (EndEvent $event) use ($io) {
                if ($this->progress instanceof ProgressBar) {
                    $this->progress->finish();
                    $io->newLine();
                }
            });

            $client->send($request);

            $zip = new ZipArchive();
            $zip->open($adapter->applyPathPrefix('images.zip'));
            $zip->extractTo($adapter->applyPathPrefix('.'));
            $zip->close();

            $this->filesystem->delete('images.zip');
        }

        $io->success('Installation finished, have fun!');

        return 0;
    }

    protected function createEnvFileInteractive(SymfonyStyle $io)
    {
        $correct = false;

        while ($correct !== true) {
            $this->createEnvFile($io);

            $io->title('The following settings have been written to the .env file:');

            $tmpEnv = [];
            foreach ($this->env as $key => $value) {
                $tmpEnv[] = [
                    $key,
                    $value,
                ];
            }
            $io->table([], $tmpEnv);

            $correct = $io->confirm('Is this information correct?');
        }

        $this->storeEnv();
    }

    protected function createEnvFile(SymfonyStyle $io)
    {
        $this->env = [];

        $io->section('Database settings');
        $this->env = array_merge($this->env, [
            'DB_HOST' => $io->ask('Enter your database host', '127.0.0.1'),
            'DB_DATABASE' => $io->ask('Enter your database name', 'swcomposer'),
            'DB_USERNAME' => $io->ask('Enter your database username', 'shopware'),
            'DB_PASSWORD' => $io->ask('Enter your database password', 'shopware'),
            'DB_PORT' => (int) $io->ask('Enter your database port number', 3306),
        ]);

        $io->section('Admin settings');
        $this->env = array_merge($this->env, [
            'ADMIN_USERNAME' => $io->ask('Admin username', 'demo'),
            'ADMIN_PASSWORD' => $io->ask('Admin password', 'demo'),
            'ADMIN_NAME' => $io->ask('Admin name', 'John Doe'),
            'ADMIN_EMAIL' => $io->ask('Admin email', 'demo@demo.com'),
        ]);

        $io->section('Shop settings');
        $this->env = array_merge($this->env, [
            'SHOP_URL' => $io->ask('Enter your shop URL incl. protocol and path', 'http://shopware.example/path'),
            'IMPORT_DEMODATA' => (bool) $io->confirm('Would you like to install demo data?') ? 'y' : 'n',
        ]);
    }

    protected function storeEnv()
    {
        $env = sprintf(
            self::ENV,
            $this->env['DB_HOST'],
            $this->env['DB_DATABASE'],
            $this->env['DB_USERNAME'],
            $this->env['DB_PASSWORD'],
            $this->env['DB_PORT'],
            $this->env['ADMIN_EMAIL'],
            $this->env['ADMIN_NAME'],
            $this->env['ADMIN_USERNAME'],
            $this->env['ADMIN_PASSWORD'],
            $this->env['SHOP_URL'],
            $this->env['IMPORT_DEMODATA']
        );

        $this->filesystem->write('.env', $env);
    }
}
